name: ci-diff-scope

on:
  pull_request:

jobs:
  check-scope:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Validate editable regions
        run: node scripts/check_safe_diff.mjs
