name: Keep Supabase Awake

on:
  schedule:
    # Every Monday at 12:00 UTC
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST endpoint
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          echo "Pinging $SUPABASE_URL"
          curl -Is "${SUPABASE_URL}" | head -n 1 || echo "Ping failed but workflow completed"

