name: CI Test
on:
  pull_request:
    branches: [ testing ]
  push:
    branches: [ testing ]
permissions:
  contents: read
  checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json — skipping install"
          fi
      - name: Build
        run: |
          if [ -f package.json ]; then
            npm run -s build || true
          else
            echo "No build step"
          fi
      - name: Test
        run: |
          if [ -f package.json ]; then
            npm test
          else:
            echo "No tests configured"
          fi
