name: Codex - Apply Pages base fix
on:
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Always fix Vite base to relative './' in production (core Pages fix)
      - name: Write vite.config.ts (relative base)
        run: |
          cat > vite.config.ts <<'EOF'
          import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react';

          const base = process.env.NODE_ENV === 'production' ? './' : '/';

          export default defineConfig({
            base,
            plugins: [react()],
            server: {
              port: 5173,
              host: true
            }
          });
          EOF

      # 2) If src/main.tsx exists, ensure canvas route works when hosted under a subpath
      - name: Patch src/main.tsx (optional)
        shell: bash
        run: |
          if [ -f src/main.tsx ]; then
            node - <<'NODE'
            const fs = require('fs');
            const p = 'src/main.tsx';
            let s = fs.readFileSync(p, 'utf8');
            if (!/normalizedPath.*visual-canvas/.test(s)) {
              // Insert normalization after the param line if present
              s = s.replace(
                /(const param = .*?;\s*)(?![^]*normalizedPath)/s,
                `$1
  const normalizedPath = url.pathname.replace(/\\/+\$/, '');
  if (normalizedPath.endsWith('/visual-canvas')) {
    return 'canvas';
  }
`
              );
              fs.writeFileSync(p, s);
              console.log('Inserted visual-canvas route normalization.');
            } else {
              console.log('Route normalization already present; skipping.');
            }
            NODE
          else
            echo "src/main.tsx not found; skipping."
          fi

      # 3) If any file references '/visual-canvas/config.json', rewrite to BASE_URL form (optional)
      - name: Rewrite visual-canvas config URL (optional, search across src/**)
        shell: bash
        run: |
          if [ -d src ]; then
            node - <<'NODE'
            const fs = require('fs');
            const path = require('path');
            const root = 'src';
            let changed = 0;
            function walk(d) {
              for (const name of fs.readdirSync(d)) {
                const full = path.join(d, name);
                const st = fs.statSync(full);
                if (st.isDirectory()) walk(full);
                else if (/\.(t|j)sx?$/.test(name)) {
                  let s = fs.readFileSync(full, 'utf8');
                  const next = s.replace(
                    /(['"`])\/visual-canvas\/config\.json\1/g,
                    '`${import.meta.env.BASE_URL}visual-canvas/config.json`'
                  );
                  if (next !== s) {
                    fs.writeFileSync(full, next);
                    changed++;
                    console.log('Patched:', full);
                  }
                }
              }
            }
            walk(root);
            console.log(`Patched files: ${changed}`);
            NODE
          else
            echo "src/ not present; skipping."
          fi

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "fix(pages): relative Vite base; optional canvas route + config URL updates"
          git push
