name: Codex – Add Canvas Entry and Deploy
on:
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  add-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Add a dedicated Visual Canvas page that mounts the canvas directly
      - name: Write visual-canvas/index.html
        run: |
          mkdir -p visual-canvas
          cat > visual-canvas/index.html <<'EOF'
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>Vibeflow Visual Canvas</title>
            </head>
            <body class="bg-neutral-900 text-gray-100">
              <div id="root"></div>
              <script type="module" src="/src/canvas.tsx"></script>
            </body>
          </html>
          EOF

      - name: Write src/canvas.tsx
        run: |
          mkdir -p src
          cat > src/canvas.tsx <<'EOF'
          import React from 'react';
          import ReactDOM from 'react-dom/client';
          import './index.css';
          // Renders the canvas directly (no query params needed)
          import VisualCanvasPage from './visual/VisualCanvasPage';

          ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
            <React.StrictMode>
              <VisualCanvasPage />
            </React.StrictMode>
          );
          EOF

      # 2) Ensure the canvas config exists under the deployed base path
      - name: Ensure canvas config
        run: |
          mkdir -p public/visual-canvas
          if [ ! -f public/visual-canvas/config.json ]; then
            cat > public/visual-canvas/config.json <<'EOF'
            {
              "lastUpdated": "",
              "groups": [
                {
                  "id": "baseline",
                  "label": "Baseline",
                  "defaultLayout": 1,
                  "variants": [
                    { "id": "main-analytics", "label": "Main Analytics", "source": "/vibeflow/?view=analytics" }
                  ]
                }
              ]
            }
            EOF
          fi

      - name: Commit added files (if any)
        run: |
          if git status --porcelain | grep -qE 'visual-canvas/index.html|src/canvas.tsx|public/visual-canvas/config.json'; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add visual-canvas/index.html src/canvas.tsx public/visual-canvas/config.json
            git commit -m "feat(canvas): add dedicated /visual-canvas entry + ensure config"
            git push
          else
            echo "No changes to commit."
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      # 3) Build with relative base so assets load under /vibeflow/
      - name: Build with relative base
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: npm run build -- --base=./

      - name: Verify dist outputs
        run: |
          test -f dist/index.html
          test -f dist/visual-canvas/index.html
          grep -q 'src="./assets/' dist/index.html || (head -n 40 dist/index.html && exit 1)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
