name: Docs Validate

on:
  push:
    branches: [ docs, main ]
  pull_request:
    branches: [ docs, main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Validate JSON Schemas (Draft 2020-12)
        run: npm run validate:schemas -- contracts/*.schema.json

      - name: Install markdown link checker
        run: npm install -g markdown-link-check

      - name: Check Markdown Links
        run: |
          find docs -name "*.md" -print0 | xargs -0 -I{} markdown-link-check -q {}
