name: Orchestrator — Dispatch to IDE (Codex)
on:
  workflow_dispatch:
    inputs:
      task_id:
        description: 'TaskContract ID (e.g., S2.1)'
        required: true
      packet_path:
        description: 'Path to prompt packet JSON (e.g., data/taskpackets/S2.1.json)'
        required: true
      assignees:
        description: 'GitHub usernames (comma-separated)'
        required: false
        default: ''
permissions:
  contents: read
  issues: write
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create issue from packet
        id: create_issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'IDE Run: ${{ inputs.task_id }} (Codex in VSCode)'
          content-filepath: ${{ inputs.packet_path }}
          labels: |
            orchestrator
            ide
            codex
          assignees: ${{ inputs.assignees }}
      - name: Comment helper
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.create_issue.outputs.issue-number }}
          body: |
            **How to run in VSCode Codex (no API key):**

            1. Open the repo in VSCode (Plus subscription).
            2. Open `${{ inputs.packet_path }}` and copy the `prompt` and `context`.
            3. Paste into Codex and ask for a minimal diff for the listed `targets`.
            4. Commit on a feature branch and open a PR.
            5. CI will regenerate the digest and enriched handoff.
