name: Promote: approved → main
on:
  push:
    branches: [ approved ]
permissions:
  contents: write
  pull-requests: write
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update PR to main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release: approved → main"
          base: main
          branch: approved
          body: "Automated release PR."
          labels: release
