name: Status Pulse (Enriched Handoff)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch: {}

# Give the workflow token write access to contents
permissions:
  contents: write
  pull-requests: write

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # keep GITHUB_TOKEN for pushes

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate repo snapshot (paths + hashes)
        run: node scripts/generate-repo-snapshot.mjs

      - name: Generate enriched handoff
        run: node scripts/generate-enriched-handoff.mjs

      # Try to commit directly to main (allowed if branch isn't protected)
      - name: Commit to main (best effort)
        id: commit
        continue-on-error: true
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/updates/handoff_ENRICHED_*.md docs/reports/repo-snapshot.json
          git commit -m "chore: enriched handoff" || echo "No changes to commit"
          git push

      # If direct push failed (403/branch protected), open a PR instead
      - name: Create PR with changes
        if: steps.commit.outcome == 'failure'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: enriched handoff (via PR)"
          branch: chore/enriched-handoff
          title: "chore: enriched handoff"
          body: |
            This PR contains the generated files:
            - `docs/reports/repo-snapshot.json`
            - `docs/updates/handoff_ENRICHED_*.md`

            Direct push to `main` failed (likely branch protection), so this PR was opened automatically.
          labels: |
            automation
            handoff
