name: Status Pulse (Enriched Handoff)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch: {}

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # These scripts avoid shell interpolation issues with backticks/${}
      - name: Generate repo snapshot (paths + hashes)
        run: node scripts/generate-repo-snapshot.mjs

      - name: Generate enriched handoff
        run: node scripts/generate-enriched-handoff.mjs

      - name: Commit handoff + snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/updates/handoff_ENRICHED_*.md docs/reports/repo-snapshot.json
          git commit -m "chore: enriched handoff" || echo "No changes"
          git push

