name: Tools Runner
on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Tool name (e.g., OpenSpecWriter@v1)'
        required: true
      args:
        description: 'JSON string of tool args'
        required: true
permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run tool
        run: |
          node scripts/toolsCli.mjs --tool "${{ inputs.tool }}" --args '${{ inputs.args }}'
      - name: Refresh digests
        run: |
          node scripts/generate-openspec-digest.mjs || true
          node scripts/generate-enriched-handoff.mjs || true
      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add openspec/changes/** docs/updates/* data/state/openspec.index.json || true
          git commit -m 'docs(openspec): tool-run update' || echo 'No changes'
          git push
