name: Visual Gate (browser-use + DevTools MCP)
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/ui/**'
      - 'docs/visual/**'
      - 'scripts/visual/**'
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  visual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run visual checks
        env:
          VF_TASK_ID: ${{ github.event.pull_request.number || 'S-PR' }}
        run: node scripts/visual/visual-run.mjs
      - name: Upload visual artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visual-${{ github.run_id }}
          path: docs/reports/visual/**
